//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public short edad { get; set; }
        public short tsangre { get; set; }
    }
}
